# Generated by Django 4.2 on 2024-05-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('1', 'pendiente'), ('2', 'en progreso'), ('3', 'completada')], default='1', max_length=1)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
